### ISSUE TITLE
Failure on noncomplete graph

### ISSUE THREAD

**Issue by Synthetica9** [rhgrant10/acopy#20]
* ACOpy version: 0.6.4
* Python version: 3.7.3
* Operating System: Linux 
  * `uname -a`: `Linux AquaRing 4.19.44 #1-NixOS SMP Thu May 16 17:41:32 UTC 2019 x86_64 GNU/Linux`

### Description

I was trying to run a solver over a noncomplete graph. I expected this to work, but it didn't. 

Alternatively, I would expect it to say loud and clear in the docs that this only works on complete graphs.

### What I Did

Minimal failing example:

```python
import acopy
import networkx as nx
import random

random.seed(0)

G = nx.cycle_graph(4)
for edge in G.edges:
    G.edges[edge]['weight'] = 1


solver = acopy.Solver()
colony = acopy.Colony()

tour = solver.solve(G, colony, limit=100)
```

Traceback:

```
Traceback (most recent call last):
  File "Untitled-1.py", line 15, in <module>
    tour = solver.solve(G, colony, limit=100)
  File "/nix/store/9yfdaw94lxrygpqqph8ry0vv2zd5dvqg-python3-3.7.3-env/lib/python3.7/site-packages/acopy/solvers.py", line 193, in solve
    for solution in self.optimize(*args, **kwargs):
  File "/nix/store/9yfdaw94lxrygpqqph8ry0vv2zd5dvqg-python3-3.7.3-env/lib/python3.7/site-packages/acopy/solvers.py", line 225, in optimize
    solutions = self.find_solutions(state.graph, state.ants)
  File "/nix/store/9yfdaw94lxrygpqqph8ry0vv2zd5dvqg-python3-3.7.3-env/lib/python3.7/site-packages/acopy/solvers.py", line 259, in find_solutions
    return [ant.tour(graph) for ant in ants]
  File "/nix/store/9yfdaw94lxrygpqqph8ry0vv2zd5dvqg-python3-3.7.3-env/lib/python3.7/site-packages/acopy/solvers.py", line 259, in <listcomp>
    return [ant.tour(graph) for ant in ants]
  File "/nix/store/9yfdaw94lxrygpqqph8ry0vv2zd5dvqg-python3-3.7.3-env/lib/python3.7/site-packages/acopy/ant.py", line 58, in tour
    solution.add_node(node)
  File "/nix/store/9yfdaw94lxrygpqqph8ry0vv2zd5dvqg-python3-3.7.3-env/lib/python3.7/site-packages/acopy/solvers.py", line 75, in add_node
    self._add_node(node)
  File "/nix/store/9yfdaw94lxrygpqqph8ry0vv2zd5dvqg-python3-3.7.3-env/lib/python3.7/site-packages/acopy/solvers.py", line 83, in _add_node
    data = self.graph.edges[edge]
  File "/nix/store/9yfdaw94lxrygpqqph8ry0vv2zd5dvqg-python3-3.7.3-env/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 930, in __getitem__
    return self._adjdict[u][v]
KeyError: 2
```

(Sorry for the mangled paths, that's NixOS for ya)

**Comment by rhgrant10** [comment]
Yes currently the algorithm doesn't support incomplete graphs. One way to work around this limitation is to assign infinite weight to missing edges.

**Comment by Synthetica9** [comment]
I see. That's not really a possibility for my use case, since I'm dealing with quite a large graph
