### ISSUE TITLE
Error: not exists edge when using networkx graph generator

### ISSUE THREAD

**Issue by Ganariya** [rhgrant10/acopy#21]
* ACOpy version: 0.6.4
* Python version: 3.6.3
* Operating System: mac

### Description

Hello.

I try to use acopy in the graph which was made by networkx.

For example

```python
import acopy
import tsplib95
import networkx as nx
import random
import matplotlib.pyplot as plt


solver = acopy.Solver(rho=.03, q=1)
colony = acopy.Colony(alpha=1, beta=3)

// try to use graph made by networkx
G = nx.fast_gnp_random_graph(10, 0.9)
for (u, v) in G.edges():
    G.edges[u, v]['weight'] = random.randint(1, 1000)

tour = solver.solve(G, colony, limit=100)

nx.draw_networkx(G)
plt.show()


print(tour.cost)
print(tour.path)

```

But when I run this code, the error occured below.

```
Traceback (most recent call last):
  File "/Users/students/Desktop/keras_aco/main.py", line 15, in <module>
    tour = solver.solve(G, colony, limit=100)
  File "/Users/students/.pyenv/versions/keras_aco_env/lib/python3.6/site-packages/acopy/solvers.py", line 193, in solve
    for solution in self.optimize(*args, **kwargs):
  File "/Users/students/.pyenv/versions/keras_aco_env/lib/python3.6/site-packages/acopy/solvers.py", line 225, in optimize
    solutions = self.find_solutions(state.graph, state.ants)
  File "/Users/students/.pyenv/versions/keras_aco_env/lib/python3.6/site-packages/acopy/solvers.py", line 259, in find_solutions
    return [ant.tour(graph) for ant in ants]
  File "/Users/students/.pyenv/versions/keras_aco_env/lib/python3.6/site-packages/acopy/solvers.py", line 259, in <listcomp>
    return [ant.tour(graph) for ant in ants]
  File "/Users/students/.pyenv/versions/keras_aco_env/lib/python3.6/site-packages/acopy/ant.py", line 57, in tour
    node = self.choose_destination(graph, solution.current, unvisited)
  File "/Users/students/.pyenv/versions/keras_aco_env/lib/python3.6/site-packages/acopy/ant.py", line 110, in choose_destination
    scores = self.get_scores(graph, current, unvisited)
  File "/Users/students/.pyenv/versions/keras_aco_env/lib/python3.6/site-packages/acopy/ant.py", line 125, in get_scores
    edge = graph.edges[current, node]
  File "/Users/students/.pyenv/versions/keras_aco_env/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 930, in __getitem__
    return self._adjdict[u][v]
KeyError: 0
```

I think that acopy's ant tried to use the edge which doesn't exists.
So, error occured.

### What I Did

Can acopy deal with the network which isn't a complete graph?

And, Can I change the code 
if Ant can't make a Hamiltonian path , then Ant trys to make a Hamiltonian path again.

Thank you, and sorry for bad english.

**Comment by rhgrant10** [comment]
Hi @Ganariya, sorry this is giving you trouble.

> Can acopy deal with the network which isn't a complete graph?

No, it only works on complete graphs.

> Can I change the code if Ant can't make a Hamiltonian path , then Ant trys to make a Hamiltonian path again.

Yes actually, there is a relatively easy way to accomplish this by subclassing the `acopy.Solver` class and using it instead. For example:

```python
import acopy


class IncompleteGraphSolver(acopy.Solver):
    """My custom solver for incomplete graphs.
    
    If the retry_limit is None then there is no limit. Careful when not setting
    this option since it means there could be infinite or otherwise time
    consuming loops.

    :param int retry_limit: maximum number of tries for each ant to find a tour
    """

    def __init__(self, retry_limit=None):
        super().__init__()
        self.retry_limit = retry_limit

    def _should_retry(self, tries):
        # return true if we should retry given the current number of tries
        if not self.retry_limit:
            return True
        return tries < self.retry_limit

    def find_solutions(self, graph, ants):
        """Return the solutions found for the given ants.

        :param graph: a graph
        :type graph: :class:`networkx.Graph`
        :param list ants: the ants to use
        :return: one solution per ant
        :rtype: list
        """
        # base implementation assumes every ant succeeds:
        # return [ant.tour(graph) for ant in ants]
        solutions = []
        tries = 0
        for ant in ants:
            # try until we have a solution or we hit the retry limit
            solution = None
            while solution is None and self._should_retry(tries):
                try:
                    solution = ants[i].tour(graph)
                except KeyError:
                    tries += 1  # try again
            # we may or may not have a solution for every ant
            if solution is not None:
                solutions.append(solution)
        return ants


# then use your custom logic
my_solver = IncompleteGraphSolver(rho=.03, q=1)
tour = my_solver.solve(G, colony, limit=100)
```

**Comment by Ganariya** [comment]
@rhgrant10 
Thank  you for replying.

This class is so beautiful, I'm so happy to know how to use python well from your code.
This class enables me to make a tour in not complete graph.

Thank you.

**Comment by andremtsilva** [comment]
Hi @rhgrant10 ,

I tried to use the custom class IncompleteGraphSolver and got the error:
NameError: name 'i' is not defined.

Then I change the iteration to properly get an ant from ants and got another error:
...line 231, in optimize
 data.sort()
TypeError: '<' not supported between instances of 'Ant' and 'Ant'

I tried some more and changed the optimizer to not use the sort method and got another error: 
line 274, in global_update
if edge in solution.path:
AttributeError: 'Ant' object has no attribute 'path'

Can you please point any direction? What am I missing here?
I really need acopy to work on an incomplete graph.

Thanks in advance

**Comment by florenttaralle** [comment]
Hi, in my opinion, there are 2 errors in the provided code above, here is a fix for it.
To be noded that this works only for quasi-fully-connected graph.
In realy sparse graphs (as the one i try to solve the TSM for) it still dosnt work.
That said i love how ACOPY's code works and is organised. This is realy elegant <3 great job on it !

``` python
import acopy


class IncompleteGraphSolver(acopy.Solver):
    """My custom solver for incomplete graphs.
    
    If the retry_limit is None then there is no limit. Careful when not setting
    this option since it means there could be infinite or otherwise time
    consuming loops.

    :param int retry_limit: maximum number of tries for each ant to find a tour
    """

    def __init__(self, rho=.03, q=1, top=None, 
        plugins=None, retry_limit=None):

        acopy.Solver.__init__(self, rho, q, top, plugins)
        self.retry_limit = retry_limit

    def _should_retry(self, tries):
        # return true if we should retry given the current number of tries
        if not self.retry_limit:
            return True
        return tries < self.retry_limit

    def find_solutions(self, graph, ants):
        """Return the solutions found for the given ants.

        :param graph: a graph
        :type graph: :class:`networkx.Graph`
        :param list ants: the ants to use
        :return: one solution per ant
        :rtype: list
        """
        # base implementation assumes every ant succeeds:
        # return [ant.tour(graph) for ant in ants]
        solutions = []
        tries = 0
        for ant in ants:
            # try until we have a solution or we hit the retry limit
            solution = None
            while solution is None and self._should_retry(tries):
                try:
                    solution = ant.tour(graph)
                except KeyError:
                    tries += 1  # try again
            # we may or may not have a solution for every ant
            if solution is not None:
                solutions.append(solution)
        return ants
```
